### ISSUE TITLE
CI: Severity: Notice  --> mysql_pconnect(): send of 5 bytes failed with errno=10053 An established connection was aborted by the software in your host machine.

### ISSUE THREAD

**Issue by lideth** [developer94/raspored#1]
hi, 
HOW to solve it?
other error happen, my config database 
$db['default']['hostname'] = 'localhost';
$db['default']['username'] = 'root';
$db['default']['password'] = '';
$db['default']['database'] = 'myDb';
$db['default']['dbdriver'] = 'mysql';
but i get error with other IP
ERROR - 03 15, 15 05:25:25 --> Query error: The user specified as a definer ('dbname'@'116.212.157.190') does not exist

how can it like that?
how to solve?
pls, help.thx

**Comment by jrocketfingers** [comment]
Oh wow, this is embarrassing.
I have totally forgotten about this repo, and I never hoped someone would dig it up amidst the vastness of github. This is a prime example of a project NOT ready to be open sourced. Anyways I was young and unaware, so I'll use that as an excuse.

Potential solution: you might have not created the database. Create a database named myDb and it might just work.

On a side note, I sincerely suggest that you do not use this as the means of learning anything. This is basically just a blank codeigniter project for all it's worth. There's more to it, but it's hardcoded and poorly done. This started as my first web application project, it is not internationalized, it is not documented; what it is, however, is a git/github exercise more than anything else.

Anyways congratuations on ending up here, if there were badges or achievements on GH you'd get one fot thoroughness. Would you mind telling me how you got here in the first place/what you were looking for? I might be able to direct you to something proper.

Cheers,
Johnny

**Comment by lideth** [comment]
oh Jonny,
i'm sorry that disturb you.I'm a new in CI and meet trouble of it then i search in google with my error message and meet your repo code look similar with my code. :(my problem:-i download source code from cpanel 
-then change config(database) for running on my localhost-it can load home but i saw in console it say "error 500 server not found"-some path got the database connection error-i go to check log it say a lot about database connection error (e.g. identify connect('usernamedb'@'IP')) that IP address and usernamedb  are not my configuration. i dont know where it come from.I was search on internet they talk about-php version,ci version, apache version(i check it seem ok)-.htaccess(am trying with this "some page can see but still get error 500 server not found"-php package(i not sure about this )

now i still not solve it :(
Anyways thank you very much that u reply me and let me say what i stuck, i will happy so much any advice from you :) thanks.

regardLideth

```
  From: Nikola Kolevski <notifications@github.com>
```

 To: developer94/raspored raspored@noreply.github.com 
Cc: lideth lideth_bb@yahoo.com 
 Sent: Sunday, March 15, 2015 7:18 PM
 Subject: Re: [raspored] CI: Severity: Notice --> mysql_pconnect(): send of 5 bytes failed with errno=10053 An established connection was aborted by the software in your host machine. (#1)

Oh wow, this is embarrassing.
I have totally forgotten about this repo, and I never hoped someone would dig it up amidst the vastness of github. This is a prime example of a project NOT ready to be open sourced. Anyways I was young and unaware, so I'll use that as an excuse.Potential solution: you might have not created the database. Create a database named myDb and it might just work.On a side note, I sincerely suggest that you do not use this as the means of learning anything. This is basically just a blank codeigniter project for all it's worth. There's more to it, but it's hardcoded and poorly done. This started as my first web application project, it is not internationalized, it is not documented; what it i, however, is a git/github exercise more than anything else.Anyways congratuations on ending up here, if there were badges or achievements on GH you'd get one fot thoroughness. Would you mind telling me how you got here in the first place/what you were looking for? I might be able to direct you to something proper.Cheers,
Johnny—

**Comment by jrocketfingers** [comment]
I tried understanding the issue, really, but I can't honestly, not with the lack of information on your sever setup. However, can I still somehow make you decide against using this codebase for anything useful? :)

One reason you found it similar to your own is because it is the default CI project layout. Not sure why would you download the source from cPanel, or even how that works. I've mainly used cPanel for administration, nothing else; especially not as a provider of PHP frameworks. You could just check out [codeigniter's website](http://www.codeigniter.com/) and perhaps find the resources/help you require.

**Comment by lideth** [comment]
:) thank you, 
i mess it so much :D. the original source code is developed by other friend, then my friend give it me look throug and help some path.
ok, i will try it again step by step
thank you very much.your reply make me so happy :D
regard
lideth

**Comment by jrocketfingers** [comment]
Well I still do not realize if I was able to help you, but I'll consider this issue unsolvable as far as the project goes. I'll be deleting it in a somewhat near future, to avoid (fortunate? :)) events such as this.
Though I'll keep it up long enough for you to make some use of it, if it is actually possible.

**Comment by lideth** [comment]
:) because I'm not good to explain my problem to you.
